test/obj/main.o: test/src/main.cpp include/datamappercpp/sql/StatementBuilder.h \
  include/datamappercpp/Field.h include/utilcpp/release_assert.h \
  include/datamappercpp/sql/detail/FieldVisitors.h \
  include/utilcpp/disable_copy.h test/testcpp/include/testcpp/testcpp.h \
  include/utilcpp/declarations.h include/utilcpp/scoped_ptr.h \
  test/testcpp/include/testcpp/assert_impl.h \
  test/testcpp/include/testcpp/StdOutView.h \
  test/testcpp/include/testcpp/detail/TextStreamTestView.h
